# Generated by Django 3.0.6 on 2020-06-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='date',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='description',
        ),
        migrations.AlterField(
            model_name='snippet',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
