# Generated by Django 3.0.6 on 2020-06-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200604_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
