# Generated by Django 3.0.6 on 2020-06-04 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_snippet_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='users',
            new_name='user',
        ),
    ]
