# Generated by Django 3.0.6 on 2020-06-07 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200604_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='visibility',
            field=models.CharField(choices=[('PUB', 'Public'), ('PRI', 'Private')], default='PRI', max_length=3),
        ),
    ]
